### ISSUE TITLE
Urbit HTTP does not run on port 8080 - which the language server wants

### ISSUE THREAD

**Issue by watbulb** [urbit/hoon-language-server#8]
As of the latest urbit releases, urbit does not seem to default bind to `8080`, and the port config for the language-server is hardcoded at `8080`. There seems to be no way to change this during the urbit VM runtime; as per: https://github.com/urbit/docs/pull/520, therefore breaking the hoon-language-server.

I'm not familiar with the internals of how this should be fixed, but for now I have forked it and changed the port myself. Is there any other more subtle way of going about this without breaking the project? Am I missing something perhaps? Sorry I'm new to the urbit ecosystem.

Thanks!

**Comment by urbitceo** [comment]
The `-p` option will change the default port:

`hoon-language-server -p 8081`

**Comment by watbulb** [comment]
when I posted it, this was not possible as the -p read a string instead of an integer, it has since been fixed two months ago. better late than never, as always with urbit.
